name: flutterchain_example
description: Demonstrates how to use the flutterchain plugin.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0
environment:
  sdk: ">=2.19.3 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  bs58: 1.0.2
  collection: ^1.17.1
  connectivity_plus: 3.0.3
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  dio_smart_retry: ^6.0.0
  easy_localization: ^3.0.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.1
  flutter_modular: 5.0.3
  flutter_screenutil: ^5.7.0
  fluentui_system_icons: ^1.1.255
  flutter_inappwebview_ios: 1.1.1
  flutterchain:
    path: ../
  hex: 0.2.0
  json_serializable: 6.6.1
  mockito: ^5.4.4
  qr_flutter: ^4.1.0
  rxdart: 0.28.0
  tap_debouncer: 2.0.2
  url_launcher: ^6.1.11
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/fonts/
    - assets/images/
    - lib/assets/icon_images/button_icons/
    - lib/assets/icon_images/nft_icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/static/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/manrope/static/Manrope-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/manrope/static/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/manrope/static/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/manrope/static/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/manrope/static/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/manrope/static/Manrope-SemiBold.ttf
          weight: 600
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
