// Mocks generated by Mockito 5.4.4 from annotations
// in flutterchain/test/unit/services/near_blockchain_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:io' as _i17;

import 'package:flutter/material.dart' as _i14;
import 'package:flutterchain/flutterchain_lib/models/chains/near/mintbase_category_nft.dart'
    as _i16;
import 'package:flutterchain/flutterchain_lib/models/chains/near/near_mpc_account_info.dart'
    as _i8;
import 'package:flutterchain/flutterchain_lib/models/chains/near/near_mpc_transaction_info.dart'
    as _i15;
import 'package:flutterchain/flutterchain_lib/models/chains/near/near_transaction_info.dart'
    as _i6;
import 'package:flutterchain/flutterchain_lib/models/core/blockchain_network_environment_settings.dart'
    as _i7;
import 'package:flutterchain/flutterchain_lib/models/core/blockchain_response.dart'
    as _i4;
import 'package:flutterchain/flutterchain_lib/models/core/blockchain_smart_contract_arguments.dart'
    as _i12;
import 'package:flutterchain/flutterchain_lib/models/core/transfer_request.dart'
    as _i11;
import 'package:flutterchain/flutterchain_lib/models/core/wallet.dart' as _i5;
import 'package:flutterchain/flutterchain_lib/network/chains/near_rpc_client.dart'
    as _i3;
import 'package:flutterchain/flutterchain_lib/services/chains/near_blockchain_service.dart'
    as _i9;
import 'package:flutterchain/flutterchain_lib/services/core/js_engines/core/js_vm.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeJsVMService_0 extends _i1.SmartFake implements _i2.JsVMService {
  _FakeJsVMService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNearRpcClient_1 extends _i1.SmartFake implements _i3.NearRpcClient {
  _FakeNearRpcClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBlockchainResponse_2 extends _i1.SmartFake
    implements _i4.BlockchainResponse {
  _FakeBlockchainResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBlockChainData_3 extends _i1.SmartFake
    implements _i5.BlockChainData {
  _FakeBlockChainData_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNearTransactionInfoModel_4 extends _i1.SmartFake
    implements _i6.NearTransactionInfoModel {
  _FakeNearTransactionInfoModel_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBlockChainNetworkEnvironmentSettings_5 extends _i1.SmartFake
    implements _i7.BlockChainNetworkEnvironmentSettings {
  _FakeBlockChainNetworkEnvironmentSettings_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMPCAccountInfo_6 extends _i1.SmartFake
    implements _i8.MPCAccountInfo {
  _FakeMPCAccountInfo_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NearBlockChainService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNearBlockChainService extends _i1.Mock
    implements _i9.NearBlockChainService {
  MockNearBlockChainService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.JsVMService get jsVMService => (super.noSuchMethod(
        Invocation.getter(#jsVMService),
        returnValue: _FakeJsVMService_0(
          this,
          Invocation.getter(#jsVMService),
        ),
      ) as _i2.JsVMService);

  @override
  _i3.NearRpcClient get nearRpcClient => (super.noSuchMethod(
        Invocation.getter(#nearRpcClient),
        returnValue: _FakeNearRpcClient_1(
          this,
          Invocation.getter(#nearRpcClient),
        ),
      ) as _i3.NearRpcClient);

  @override
  _i10.Future<_i4.BlockchainResponse> sendTransferNativeCoin(
          _i11.TransferRequest? transferRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendTransferNativeCoin,
          [transferRequest],
        ),
        returnValue:
            _i10.Future<_i4.BlockchainResponse>.value(_FakeBlockchainResponse_2(
          this,
          Invocation.method(
            #sendTransferNativeCoin,
            [transferRequest],
          ),
        )),
      ) as _i10.Future<_i4.BlockchainResponse>);

  @override
  _i10.Future<_i4.BlockchainResponse> callSmartContractFunction(
          _i12.BlockChainSmartContractArguments? smartContractArguments) =>
      (super.noSuchMethod(
        Invocation.method(
          #callSmartContractFunction,
          [smartContractArguments],
        ),
        returnValue:
            _i10.Future<_i4.BlockchainResponse>.value(_FakeBlockchainResponse_2(
          this,
          Invocation.method(
            #callSmartContractFunction,
            [smartContractArguments],
          ),
        )),
      ) as _i10.Future<_i4.BlockchainResponse>);

  @override
  _i10.Future<_i4.BlockchainResponse> callViewMethod({
    required String? contractId,
    required String? method,
    Map<String, dynamic>? args = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #callViewMethod,
          [],
          {
            #contractId: contractId,
            #method: method,
            #args: args,
          },
        ),
        returnValue:
            _i10.Future<_i4.BlockchainResponse>.value(_FakeBlockchainResponse_2(
          this,
          Invocation.method(
            #callViewMethod,
            [],
            {
              #contractId: contractId,
              #method: method,
              #args: args,
            },
          ),
        )),
      ) as _i10.Future<_i4.BlockchainResponse>);

  @override
  _i10.Future<String> getWalletBalance(_i11.TransferRequest? transferRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWalletBalance,
          [transferRequest],
        ),
        returnValue: _i10.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #getWalletBalance,
            [transferRequest],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<void> setBlockchainNetworkEnvironment(
          _i7.BlockChainNetworkEnvironmentSettings?
              blockChainNetworkEnvironmentSettings) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBlockchainNetworkEnvironment,
          [blockChainNetworkEnvironmentSettings],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  Set<String> getBlockchainsUrlsByBlockchainType() => (super.noSuchMethod(
        Invocation.method(
          #getBlockchainsUrlsByBlockchainType,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  _i10.Future<_i5.BlockChainData> getBlockChainData({
    required String? mnemonic,
    String? passphrase,
    _i5.DerivationPathData? derivationPath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBlockChainData,
          [],
          {
            #mnemonic: mnemonic,
            #passphrase: passphrase,
            #derivationPath: derivationPath,
          },
        ),
        returnValue:
            _i10.Future<_i5.BlockChainData>.value(_FakeBlockChainData_3(
          this,
          Invocation.method(
            #getBlockChainData,
            [],
            {
              #mnemonic: mnemonic,
              #passphrase: passphrase,
              #derivationPath: derivationPath,
            },
          ),
        )),
      ) as _i10.Future<_i5.BlockChainData>);

  @override
  _i10.Future<_i6.NearTransactionInfoModel> getTransactionInfo({
    required String? accountId,
    required String? publicKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionInfo,
          [],
          {
            #accountId: accountId,
            #publicKey: publicKey,
          },
        ),
        returnValue: _i10.Future<_i6.NearTransactionInfoModel>.value(
            _FakeNearTransactionInfoModel_4(
          this,
          Invocation.method(
            #getTransactionInfo,
            [],
            {
              #accountId: accountId,
              #publicKey: publicKey,
            },
          ),
        )),
      ) as _i10.Future<_i6.NearTransactionInfoModel>);

  @override
  _i10.Future<_i4.BlockchainResponse> sendTransactionNearSync(
          {required List<String>? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendTransactionNearSync,
          [],
          {#params: params},
        ),
        returnValue:
            _i10.Future<_i4.BlockchainResponse>.value(_FakeBlockchainResponse_2(
          this,
          Invocation.method(
            #sendTransactionNearSync,
            [],
            {#params: params},
          ),
        )),
      ) as _i10.Future<_i4.BlockchainResponse>);

  @override
  _i10.Future<_i4.BlockchainResponse> sendTransactionNearAsync(
          {required List<String>? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendTransactionNearAsync,
          [],
          {#params: params},
        ),
        returnValue:
            _i10.Future<_i4.BlockchainResponse>.value(_FakeBlockchainResponse_2(
          this,
          Invocation.method(
            #sendTransactionNearAsync,
            [],
            {#params: params},
          ),
        )),
      ) as _i10.Future<_i4.BlockchainResponse>);

  @override
  _i10.Future<String> signNearActions({
    required String? fromAddress,
    required String? toAddress,
    required String? transferAmount,
    required String? privateKey,
    required String? gas,
    required int? nonce,
    required String? blockHash,
    required List<Map<String, dynamic>>? actions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signNearActions,
          [],
          {
            #fromAddress: fromAddress,
            #toAddress: toAddress,
            #transferAmount: transferAmount,
            #privateKey: privateKey,
            #gas: gas,
            #nonce: nonce,
            #blockHash: blockHash,
            #actions: actions,
          },
        ),
        returnValue: _i10.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #signNearActions,
            [],
            {
              #fromAddress: fromAddress,
              #toAddress: toAddress,
              #transferAmount: transferAmount,
              #privateKey: privateKey,
              #gas: gas,
              #nonce: nonce,
              #blockHash: blockHash,
              #actions: actions,
            },
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<_i4.BlockchainResponse> deleteKey({
    required String? accountId,
    required String? deletedPublicKey,
    required String? privateKey,
    required String? publicKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteKey,
          [],
          {
            #accountId: accountId,
            #deletedPublicKey: deletedPublicKey,
            #privateKey: privateKey,
            #publicKey: publicKey,
          },
        ),
        returnValue:
            _i10.Future<_i4.BlockchainResponse>.value(_FakeBlockchainResponse_2(
          this,
          Invocation.method(
            #deleteKey,
            [],
            {
              #accountId: accountId,
              #deletedPublicKey: deletedPublicKey,
              #privateKey: privateKey,
              #publicKey: publicKey,
            },
          ),
        )),
      ) as _i10.Future<_i4.BlockchainResponse>);

  @override
  _i10.Future<_i4.BlockchainResponse> addKey({
    required String? fromAddress,
    required String? mnemonic,
    String? passphrase = r'',
    required _i5.DerivationPath? derivationPathOfNewGeneratedAccount,
    required String? permission,
    required String? allowance,
    required String? smartContractId,
    required List<String>? methodNames,
    required String? privateKey,
    required String? publicKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addKey,
          [],
          {
            #fromAddress: fromAddress,
            #mnemonic: mnemonic,
            #passphrase: passphrase,
            #derivationPathOfNewGeneratedAccount:
                derivationPathOfNewGeneratedAccount,
            #permission: permission,
            #allowance: allowance,
            #smartContractId: smartContractId,
            #methodNames: methodNames,
            #privateKey: privateKey,
            #publicKey: publicKey,
          },
        ),
        returnValue:
            _i10.Future<_i4.BlockchainResponse>.value(_FakeBlockchainResponse_2(
          this,
          Invocation.method(
            #addKey,
            [],
            {
              #fromAddress: fromAddress,
              #mnemonic: mnemonic,
              #passphrase: passphrase,
              #derivationPathOfNewGeneratedAccount:
                  derivationPathOfNewGeneratedAccount,
              #permission: permission,
              #allowance: allowance,
              #smartContractId: smartContractId,
              #methodNames: methodNames,
              #privateKey: privateKey,
              #publicKey: publicKey,
            },
          ),
        )),
      ) as _i10.Future<_i4.BlockchainResponse>);

  @override
  _i10.Future<String> exportPrivateKeyToTheNearApiJsFormat(
          {_i5.BlockChainData? currentBlockchainData}) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportPrivateKeyToTheNearApiJsFormat,
          [],
          {#currentBlockchainData: currentBlockchainData},
        ),
        returnValue: _i10.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #exportPrivateKeyToTheNearApiJsFormat,
            [],
            {#currentBlockchainData: currentBlockchainData},
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<String> getBase58PubKeyFromHexValue(
          {required String? hexEncodedPubKey}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBase58PubKeyFromHexValue,
          [],
          {#hexEncodedPubKey: hexEncodedPubKey},
        ),
        returnValue: _i10.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #getBase58PubKeyFromHexValue,
            [],
            {#hexEncodedPubKey: hexEncodedPubKey},
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<String> getPublicKeyFromSecretKeyFromNearApiJSFormat(
          String? base58PrivateKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPublicKeyFromSecretKeyFromNearApiJSFormat,
          [base58PrivateKey],
        ),
        returnValue: _i10.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #getPublicKeyFromSecretKeyFromNearApiJSFormat,
            [base58PrivateKey],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<String> getPrivateKeyFromSecretKeyFromNearApiJSFormat(
          String? base58PrivateKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrivateKeyFromSecretKeyFromNearApiJSFormat,
          [base58PrivateKey],
        ),
        returnValue: _i10.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #getPrivateKeyFromSecretKeyFromNearApiJSFormat,
            [base58PrivateKey],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<_i7.BlockChainNetworkEnvironmentSettings>
      getBlockchainNetworkEnvironment() => (super.noSuchMethod(
            Invocation.method(
              #getBlockchainNetworkEnvironment,
              [],
            ),
            returnValue:
                _i10.Future<_i7.BlockChainNetworkEnvironmentSettings>.value(
                    _FakeBlockChainNetworkEnvironmentSettings_5(
              this,
              Invocation.method(
                #getBlockchainNetworkEnvironment,
                [],
              ),
            )),
          ) as _i10.Future<_i7.BlockChainNetworkEnvironmentSettings>);

  @override
  _i10.Future<void> authWithNearWalletsWeb(
    String? privateNearAPIjsFormat, [
    String? successUrlCallBackWeb,
    String? failureUrlCallBackWeb,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #authWithNearWalletsWeb,
          [
            privateNearAPIjsFormat,
            successUrlCallBackWeb,
            failureUrlCallBackWeb,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<String> authWithNearWallets(
    _i14.BuildContext? context,
    String? privateNearAPIjsFormat,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #authWithNearWallets,
          [
            context,
            privateNearAPIjsFormat,
          ],
        ),
        returnValue: _i10.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #authWithNearWallets,
            [
              context,
              privateNearAPIjsFormat,
            ],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<_i8.MPCAccountInfo> getMPCAccount({
    required String? accountId,
    String? path = r'flutterchain',
    String? chain = r'ETHEREUM',
    String? typeOfNetwork = r'testnet',
    String? mpcPublicKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMPCAccount,
          [],
          {
            #accountId: accountId,
            #path: path,
            #chain: chain,
            #typeOfNetwork: typeOfNetwork,
            #mpcPublicKey: mpcPublicKey,
          },
        ),
        returnValue:
            _i10.Future<_i8.MPCAccountInfo>.value(_FakeMPCAccountInfo_6(
          this,
          Invocation.method(
            #getMPCAccount,
            [],
            {
              #accountId: accountId,
              #path: path,
              #chain: chain,
              #typeOfNetwork: typeOfNetwork,
              #mpcPublicKey: mpcPublicKey,
            },
          ),
        )),
      ) as _i10.Future<_i8.MPCAccountInfo>);

  @override
  _i10.Future<String> signEVMTransationWithMPC({
    required String? accountId,
    required String? publicKey,
    required String? privateKey,
    required _i15.MpcTransactionInfo? mpcTransactionInfo,
    required String? senderAdress,
    String? path = r'flutterchain',
    String? mpcContract = r'v2.multichain-mpc.testnet',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signEVMTransationWithMPC,
          [],
          {
            #accountId: accountId,
            #publicKey: publicKey,
            #privateKey: privateKey,
            #mpcTransactionInfo: mpcTransactionInfo,
            #senderAdress: senderAdress,
            #path: path,
            #mpcContract: mpcContract,
          },
        ),
        returnValue: _i10.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #signEVMTransationWithMPC,
            [],
            {
              #accountId: accountId,
              #publicKey: publicKey,
              #privateKey: privateKey,
              #mpcTransactionInfo: mpcTransactionInfo,
              #senderAdress: senderAdress,
              #path: path,
              #mpcContract: mpcContract,
            },
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<String> signBTCTransactionWithMPC({
    required String? accountId,
    required String? publicKey,
    required String? privateKey,
    required _i15.MpcTransactionInfo? transactionInfo,
    required String? mpcSenderPublicKey,
    String? path = r'flutterchain',
    String? mpcContract = r'v2.multichain-mpc.testnet',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signBTCTransactionWithMPC,
          [],
          {
            #accountId: accountId,
            #publicKey: publicKey,
            #privateKey: privateKey,
            #transactionInfo: transactionInfo,
            #mpcSenderPublicKey: mpcSenderPublicKey,
            #path: path,
            #mpcContract: mpcContract,
          },
        ),
        returnValue: _i10.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #signBTCTransactionWithMPC,
            [],
            {
              #accountId: accountId,
              #publicKey: publicKey,
              #privateKey: privateKey,
              #transactionInfo: transactionInfo,
              #mpcSenderPublicKey: mpcSenderPublicKey,
              #path: path,
              #mpcContract: mpcContract,
            },
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<String> signXRPTransactionWithMPC({
    required String? accountId,
    required String? publicKey,
    required String? privateKey,
    required _i15.MpcTransactionInfo? mpcTransactionInfo,
    String? path = r'flutterchain',
    String? mpcContract = r'v2.multichain-mpc.testnet',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signXRPTransactionWithMPC,
          [],
          {
            #accountId: accountId,
            #publicKey: publicKey,
            #privateKey: privateKey,
            #mpcTransactionInfo: mpcTransactionInfo,
            #path: path,
            #mpcContract: mpcContract,
          },
        ),
        returnValue: _i10.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #signXRPTransactionWithMPC,
            [],
            {
              #accountId: accountId,
              #publicKey: publicKey,
              #privateKey: privateKey,
              #mpcTransactionInfo: mpcTransactionInfo,
              #path: path,
              #mpcContract: mpcContract,
            },
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<bool> deployNFTCollection({
    required String? accountId,
    required String? publicKey,
    required String? privateKey,
    required String? symbol,
    required String? name,
    required String? ownerId,
    String? spec = r'nft-1.0.0',
    String? icon =
        r'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAEXUlEQVRYR8VXW4hVVRj+vrX3OYbFNBl2eSsoa8pkxMJmzpGGoIwMY0wwImuCXmKKkiikKayHQIpAwbdAswskBYqJSlANek7TUOPURGKCWdmFkJnsoZnhzNn/F2vcZ9gez2UfEVoP+2Gv///Xt771X4mUq6enpz2Kogck3S2pk+R1ki736iT/kfQzyW/N7PNsNrtvcHDwTBrTbCbU1dV1cxiGGyWtA3BJM/l4f1rSLjPbPDQ0dKyRTl0AS5YsubStre11AP0AwiYHi+SJmJGFCdmypG3T09MDIyMjk7Vs1ASQy+VuIrkbQEezG3vqJfXGTzHhnFtlZttIuoTuUQC9hULheLW98wDkcrnbARwkeWWzw+P9ewCsB/AYgBkz6yW5lmRfUl/SOMmVhUJhJPn/HAD+5gCKLRzubS0AMO59MTa828z2Oud2VF8gBtGdZGIOQPzmX6ehPWk4iqKOIAg+BnCr/y/pJUmnnHPv1WHw6NTU1B0Vn5gDkM/ntwB4NiXtc2KS9kdR1B+G4aMA/pD0kaQHGwDwILcUi8UNs37jPz7UgiD4PoW318Qn6QSA/STbJc2T9EkjAAB8dCwuFos/zgLI5/M7YydqlYBa8vvMbFcTAJ6FncVisY/5fP4KT10LSaYZyFQAAEyHYXitB+BD6N1mVlvYTwsAZraeuVxuR3XMNjpM0mFJW0n+VUfub0mnSS6S5JxznQBeBpDMkBXV7R7AKEkv1HRJGiLpvX0rgHYzGyB5S5yuZ/VJHioUCv25XO4Vn/0AHDCzD51z35DMViWnUf8EEwC8H6RZj5O8Py5M3pF+D4JghZn9lFDeB+AtAF9U/vmw9CBJ3lt1yIQHYIks1gzEapJPSlodJ53xcrncmclkTiUOOwRgM8n9iX8Pk/S+tqqKAWsZgJmddM6971kzs+f9W5P0VbOyZmZmZjyo5yStcc4djKJoE8kxkvNrAWjlCVZLugHAYefcpJmtIzkAIKii7ldJL5jZkTAMF0t6A8CNNeidaMkJAXjqNwLobvZWafYljbYahhcVAIDtrSaiiwpgNhGlSMVjAI5J8m3Xm3FILapD8UKSd9XwiVriZ1Ox36lXjCRtMLPPwjC8s1QqHRgeHv6tu7v7IefcNYkQG8tkMqPlcnmNrylm9q9z7lMAlzXyg7li5IXqlOOvADwN4EsAPoOdLpVKHdlsdm/SCUku8/UdwIo4NzxF8noALzYAcG45jlmobkjelnTc014xRPI+Sa8BWJ4w7lsyH8qVtUfSHpLv1ANwXkPiBWu0ZEeiKOoLgsAzMd+nXTNb7pz7geTsQBLfuIvkqwBWnu3I9ASAZSSfqQOgdkvmhaubUpKboij6IAiCpSSH/aAB4JEqw9+VSqXeTCZzm6Q/nXNXA/A94rxqAA2b0opwjbb8JADfzy8FcFWdW01K8kwtqFdZU7XlCRCpB5M0GQ9A+sGkYrDF0awejgsbzZLW/rfhtPpKTcbzM5J+uZDx/D8+0FUx/4DhyAAAAABJRU5ErkJggg==',
    String? baseUri = r'https://arweave.net',
    String? reference,
    String? referenceHash,
    String? factoryContract,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deployNFTCollection,
          [],
          {
            #accountId: accountId,
            #publicKey: publicKey,
            #privateKey: privateKey,
            #symbol: symbol,
            #name: name,
            #ownerId: ownerId,
            #spec: spec,
            #icon: icon,
            #baseUri: baseUri,
            #reference: reference,
            #referenceHash: referenceHash,
            #factoryContract: factoryContract,
          },
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<List<dynamic>> checkOwnerCollection(
          {required String? owner_id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkOwnerCollection,
          [],
          {#owner_id: owner_id},
        ),
        returnValue: _i10.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i10.Future<List<dynamic>>);

  @override
  _i10.Future<List<dynamic>> checkMinterCollection(
          {required String? owner_id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkMinterCollection,
          [],
          {#owner_id: owner_id},
        ),
        returnValue: _i10.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i10.Future<List<dynamic>>);

  @override
  _i10.Future<List<dynamic>> checkNFTInfo({required String? owner_id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkNFTInfo,
          [],
          {#owner_id: owner_id},
        ),
        returnValue: _i10.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i10.Future<List<dynamic>>);

  @override
  _i10.Future<List<dynamic>> checkListingNFT({required String? ownerId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkListingNFT,
          [],
          {#ownerId: ownerId},
        ),
        returnValue: _i10.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i10.Future<List<dynamic>>);

  @override
  _i10.Future<Map<String, String>> checkMaxPriceBidNFT({
    required String? nftContractId,
    required int? tokenId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkMaxPriceBidNFT,
          [],
          {
            #nftContractId: nftContractId,
            #tokenId: tokenId,
          },
        ),
        returnValue: _i10.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i10.Future<Map<String, String>>);

  @override
  _i10.Future<dynamic> transferNFTCollection({
    required String? accountId,
    required String? publicKey,
    required String? privateKey,
    required String? nftCollectionContract,
    required String? new_owner,
    required bool? keep_old_minters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transferNFTCollection,
          [],
          {
            #accountId: accountId,
            #publicKey: publicKey,
            #privateKey: privateKey,
            #nftCollectionContract: nftCollectionContract,
            #new_owner: new_owner,
            #keep_old_minters: keep_old_minters,
          },
        ),
        returnValue: _i10.Future<dynamic>.value(),
      ) as _i10.Future<dynamic>);

  @override
  _i10.Future<dynamic> addDeleteMinters({
    required String? accountId,
    required String? publicKey,
    required String? privateKey,
    required String? nftCollectionContract,
    required String? name,
    required bool? isAdd,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDeleteMinters,
          [],
          {
            #accountId: accountId,
            #publicKey: publicKey,
            #privateKey: privateKey,
            #nftCollectionContract: nftCollectionContract,
            #name: name,
            #isAdd: isAdd,
          },
        ),
        returnValue: _i10.Future<dynamic>.value(),
      ) as _i10.Future<dynamic>);

  @override
  _i10.Future<List<dynamic>> getMinters({
    required String? accountId,
    required String? publicKey,
    required String? privateKey,
    required String? nftCollectionContract,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMinters,
          [],
          {
            #accountId: accountId,
            #publicKey: publicKey,
            #privateKey: privateKey,
            #nftCollectionContract: nftCollectionContract,
          },
        ),
        returnValue: _i10.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i10.Future<List<dynamic>>);

  @override
  _i10.Future<bool> mintNFT({
    required String? accountId,
    required String? publicKey,
    required String? privateKey,
    required String? nftCollectionContract,
    required String? owner_id,
    required String? description,
    required String? title,
    required String? media,
    String? media_type,
    String? animation,
    int? num_to_mint = 1,
    Map<String, int>? split_between,
    Map<String, int>? split_owners,
    List<String>? tags,
    List<dynamic>? extra,
    _i16.CategoryNFT? category,
    String? document,
    String? baseURL = r'https://arweave.net/',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #mintNFT,
          [],
          {
            #accountId: accountId,
            #publicKey: publicKey,
            #privateKey: privateKey,
            #nftCollectionContract: nftCollectionContract,
            #owner_id: owner_id,
            #description: description,
            #title: title,
            #media: media,
            #media_type: media_type,
            #animation: animation,
            #num_to_mint: num_to_mint,
            #split_between: split_between,
            #split_owners: split_owners,
            #tags: tags,
            #extra: extra,
            #category: category,
            #document: document,
            #baseURL: baseURL,
          },
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  String mintingDeposit({
    required int? nSplits,
    required int? nTokens,
    required int? nRoyalties,
    required Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #mintingDeposit,
          [],
          {
            #nSplits: nSplits,
            #nTokens: nTokens,
            #nRoyalties: nRoyalties,
            #metadata: metadata,
          },
        ),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.method(
            #mintingDeposit,
            [],
            {
              #nSplits: nSplits,
              #nTokens: nTokens,
              #nRoyalties: nRoyalties,
              #metadata: metadata,
            },
          ),
        ),
      ) as String);

  @override
  _i10.Future<String> uploadFileToArweave({required _i17.File? file}) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFileToArweave,
          [],
          {#file: file},
        ),
        returnValue: _i10.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #uploadFileToArweave,
            [],
            {#file: file},
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<Map<String, dynamic>> uploadReferenceToArweave(
          {required Map<String, dynamic>? reference}) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadReferenceToArweave,
          [],
          {#reference: reference},
        ),
        returnValue:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i10.Future<Map<String, dynamic>>);

  @override
  Map<String, int> calculateRoyalty({
    required Map<String, int>? noCompletelyRoyalty,
    required int? totalSum,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateRoyalty,
          [],
          {
            #noCompletelyRoyalty: noCompletelyRoyalty,
            #totalSum: totalSum,
          },
        ),
        returnValue: <String, int>{},
      ) as Map<String, int>);

  @override
  _i10.Future<bool> transferNFT({
    required String? accountId,
    required String? publicKey,
    required String? privateKey,
    required String? nftCollectionContract,
    required List<List<String>>? tokenIds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transferNFT,
          [],
          {
            #accountId: accountId,
            #publicKey: publicKey,
            #privateKey: privateKey,
            #nftCollectionContract: nftCollectionContract,
            #tokenIds: tokenIds,
          },
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<_i4.BlockchainResponse> NFTInteractionPermission({
    required String? nameNFTCollection,
    required String? tokenId,
    required String? ownerId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #NFTInteractionPermission,
          [],
          {
            #nameNFTCollection: nameNFTCollection,
            #tokenId: tokenId,
            #ownerId: ownerId,
          },
        ),
        returnValue:
            _i10.Future<_i4.BlockchainResponse>.value(_FakeBlockchainResponse_2(
          this,
          Invocation.method(
            #NFTInteractionPermission,
            [],
            {
              #nameNFTCollection: nameNFTCollection,
              #tokenId: tokenId,
              #ownerId: ownerId,
            },
          ),
        )),
      ) as _i10.Future<_i4.BlockchainResponse>);

  @override
  _i10.Future<bool> multiplyNFT({
    required String? nameNFTCollection,
    required String? nameNFT,
    required String? accountId,
    required String? publicKey,
    required String? privateKey,
    required int? numToMint,
    String? media,
    String? reference,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #multiplyNFT,
          [],
          {
            #nameNFTCollection: nameNFTCollection,
            #nameNFT: nameNFT,
            #accountId: accountId,
            #publicKey: publicKey,
            #privateKey: privateKey,
            #numToMint: numToMint,
            #media: media,
            #reference: reference,
          },
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<_i4.BlockchainResponse> getInfoForMultiply({
    required String? nameNFTCollection,
    required String? ownerId,
    required String? nameNFT,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInfoForMultiply,
          [],
          {
            #nameNFTCollection: nameNFTCollection,
            #ownerId: ownerId,
            #nameNFT: nameNFT,
          },
        ),
        returnValue:
            _i10.Future<_i4.BlockchainResponse>.value(_FakeBlockchainResponse_2(
          this,
          Invocation.method(
            #getInfoForMultiply,
            [],
            {
              #nameNFTCollection: nameNFTCollection,
              #ownerId: ownerId,
              #nameNFT: nameNFT,
            },
          ),
        )),
      ) as _i10.Future<_i4.BlockchainResponse>);

  @override
  _i10.Future<bool> simpleListNFT({
    required String? nameNFTCollection,
    required String? tokenId,
    required String? price,
    required String? accountId,
    required String? publicKey,
    required String? privateKey,
    String? market_account_id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #simpleListNFT,
          [],
          {
            #nameNFTCollection: nameNFTCollection,
            #tokenId: tokenId,
            #price: price,
            #accountId: accountId,
            #publicKey: publicKey,
            #privateKey: privateKey,
            #market_account_id: market_account_id,
          },
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> listingActivate({
    required String? accountId,
    required String? publicKey,
    required String? privateKey,
    String? market_account_id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listingActivate,
          [],
          {
            #accountId: accountId,
            #publicKey: publicKey,
            #privateKey: privateKey,
            #market_account_id: market_account_id,
          },
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> unlistNFT({
    required String? accountId,
    required String? publicKey,
    required String? nameNFTCollection,
    required String? privateKey,
    required int? tokenId,
    String? market_account_id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #unlistNFT,
          [],
          {
            #accountId: accountId,
            #publicKey: publicKey,
            #nameNFTCollection: nameNFTCollection,
            #privateKey: privateKey,
            #tokenId: tokenId,
            #market_account_id: market_account_id,
          },
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> delistNFT({
    required String? accountId,
    required String? publicKey,
    required String? nameNFTCollection,
    required String? privateKey,
    required int? tokenId,
    String? market_account_id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delistNFT,
          [],
          {
            #accountId: accountId,
            #publicKey: publicKey,
            #nameNFTCollection: nameNFTCollection,
            #privateKey: privateKey,
            #tokenId: tokenId,
            #market_account_id: market_account_id,
          },
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> buySimpleListNFT({
    required String? accountId,
    required String? publicKey,
    required String? nameNFTCollection,
    required String? privateKey,
    required int? tokenId,
    String? referrer_id,
    String? market_account_id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #buySimpleListNFT,
          [],
          {
            #accountId: accountId,
            #publicKey: publicKey,
            #nameNFTCollection: nameNFTCollection,
            #privateKey: privateKey,
            #tokenId: tokenId,
            #referrer_id: referrer_id,
            #market_account_id: market_account_id,
          },
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<String> getPriceForBuySimpleListNFT({
    required String? nftContractId,
    required int? tokenId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPriceForBuySimpleListNFT,
          [],
          {
            #nftContractId: nftContractId,
            #tokenId: tokenId,
          },
        ),
        returnValue: _i10.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #getPriceForBuySimpleListNFT,
            [],
            {
              #nftContractId: nftContractId,
              #tokenId: tokenId,
            },
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<bool> rollingAuctionNft({
    required String? accountId,
    required String? publicKey,
    required String? nameNFTCollection,
    required String? privateKey,
    required int? tokenId,
    required String? price,
    String? market_account_id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rollingAuctionNft,
          [],
          {
            #accountId: accountId,
            #publicKey: publicKey,
            #nameNFTCollection: nameNFTCollection,
            #privateKey: privateKey,
            #tokenId: tokenId,
            #price: price,
            #market_account_id: market_account_id,
          },
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> offersToRollingAuction({
    required String? accountId,
    required String? publicKey,
    required String? nameNFTCollection,
    required String? privateKey,
    required int? tokenId,
    required String? priceBid,
    int? timeoutInHours,
    String? market_account_id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #offersToRollingAuction,
          [],
          {
            #accountId: accountId,
            #publicKey: publicKey,
            #nameNFTCollection: nameNFTCollection,
            #privateKey: privateKey,
            #tokenId: tokenId,
            #priceBid: priceBid,
            #timeoutInHours: timeoutInHours,
            #market_account_id: market_account_id,
          },
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);
}
